import { GoalItem, AIRecommendation, MilestoneItem } from './types';

export const INITIAL_GOALS: GoalItem[] = [
  {
    id: 'goal-1',
    title: 'Project Alpha Launch',
    category: 'Work',
    description: 'Launch the new Project Alpha platform for beta users.',
    progress: 68,
    targetDate: 'Jun 30, 2025',
    priority: 'High priority',
    status: 'at_risk',
    iconType: 'rocket',
    iconTheme: 'purple',
    successMetric: '1,000 active beta users with >85% satisfaction score',
    nextAction: {
      title: 'Finalize pricing strategy',
      time: 'Today',
      type: 'document',
      context: 'Review Tier 1 enterprise pricing structure before afternoon client sync.',
    },
    connectedSources: [
      {
        id: 'src-1-1',
        type: 'gmail',
        name: 'Gmail',
        detail: 'Thread: Re: Alpha Launch Timeline & SLA Terms',
        snippet: 'Rahul: "Let\'s lock in the SLA tier by Friday so we can sign off on beta access."',
        time: '2 hours ago',
      },
      {
        id: 'src-1-2',
        type: 'calendar',
        name: 'Google Calendar',
        detail: 'Project Alpha Sync (Weekly Alignment)',
        snippet: '4 attendees confirmed: Rahul, Sarah Jenkins, Dev Lead, Product Lead',
        time: 'Today, 9:30 AM',
      },
      {
        id: 'src-1-3',
        type: 'drive',
        name: 'Google Drive',
        detail: 'Alpha_Platform_Architecture_v3.pdf',
        snippet: '14-page technical specification updated by backend engineering',
        time: 'Yesterday',
      },
      {
        id: 'src-1-4',
        type: 'notion',
        name: 'Notion',
        detail: 'Project Alpha Master Roadmap & Sprint Log',
        snippet: 'Sprint 14 backlog: 8/12 user stories completed',
        time: '3 hours ago',
      },
    ],
    moreSourcesCount: 2,
    milestones: [
      {
        id: 'm-1-1',
        title: 'Complete Core API & Auth Migration',
        targetDate: 'Apr 15, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
      {
        id: 'm-1-2',
        title: 'Finalize Pricing & SLA Strategy',
        targetDate: 'May 20, 2025',
        daysRemaining: 4,
        isCompleted: false,
        status: 'in_progress',
      },
      {
        id: 'm-1-3',
        title: 'Internal Dogfooding & QA Signoff',
        targetDate: 'Jun 10, 2025',
        daysRemaining: 25,
        isCompleted: false,
        status: 'upcoming',
      },
      {
        id: 'm-1-4',
        title: 'Public Beta Launch on Product Hunt',
        targetDate: 'Jun 30, 2025',
        daysRemaining: 45,
        isCompleted: false,
        status: 'upcoming',
      },
    ],
    aiReasoning:
      'Nexorbit detected 3 unresolved dependency threads in Gmail and an upcoming client sync. Finishing the pricing tier today unlocks the next 2 milestones.',
    blockers: [
      'Awaiting legal sign-off on enterprise indemnity clause in Drive contract draft.',
      'Pricing model needs final confirmation with Product Strategy.',
    ],
    synapticInsights: {
      driveFiles: ['Alpha_Platform_Architecture_v3.pdf', 'Pricing_Tier_Matrix_Draft.xlsx', 'Alpha_Beta_Agreement_v2.docx'],
      emails: ['Re: Alpha Launch Timeline & SLA Terms (Rahul)', 'DevOps Migration Status Report', 'QA Regression Test Matrix'],
      calendarEvents: ['Project Alpha Sync (9:30 AM)', 'Pricing Review with Strategy (1:00 PM)'],
      notionPages: ['Project Alpha Master Roadmap', 'Beta Cohort 1 Feedback Log'],
    },
  },
  {
    id: 'goal-2',
    title: 'Improve Client Satisfaction',
    category: 'Work',
    description: 'Increase client NPS score to 60+ this quarter.',
    progress: 42,
    targetDate: 'Jun 30, 2025',
    priority: 'Medium priority',
    status: 'at_risk',
    iconType: 'users',
    iconTheme: 'emerald',
    successMetric: 'NPS >= 60 with <4h response time across enterprise tickets',
    nextAction: {
      title: 'Review recent client feedback',
      time: 'Tomorrow',
      type: 'email',
      context: 'Synthesize feedback notes from the 4 most recent enterprise onboardings.',
    },
    connectedSources: [
      {
        id: 'src-2-1',
        type: 'gmail',
        name: 'Gmail',
        detail: 'Feedback Summary from Q2 Cohort',
        snippet: 'NPS comments collected across 18 accounts; 3 urgent escalation items flagged',
        time: 'Yesterday',
      },
      {
        id: 'src-2-2',
        type: 'drive',
        name: 'Google Drive',
        detail: 'Client_Health_Scorecard_Q2.xlsx',
        snippet: 'Updated satisfaction metrics showing 52 NPS baseline (+8 needed)',
        time: '2 days ago',
      },
      {
        id: 'src-2-3',
        type: 'notion',
        name: 'Notion',
        detail: 'Client Escalation Protocols & FAQ Guide',
        snippet: 'Standardized resolution templates for support and solutions teams',
        time: 'May 10',
      },
    ],
    moreSourcesCount: 1,
    milestones: [
      {
        id: 'm-2-1',
        title: 'Establish Weekly Feedback Review Loop',
        targetDate: 'May 05, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
      {
        id: 'm-2-2',
        title: 'Implement Under-4-Hour SLA Routing',
        targetDate: 'Jun 01, 2025',
        daysRemaining: 16,
        isCompleted: false,
        status: 'in_progress',
      },
      {
        id: 'm-2-3',
        title: 'Achieve NPS 60 in Quarterly Survey',
        targetDate: 'Jun 30, 2025',
        daysRemaining: 45,
        isCompleted: false,
        status: 'upcoming',
      },
    ],
    aiReasoning:
      'Current velocity indicates an estimated finish at NPS 54. Delegating routine ticket triage can free up 6h weekly for high-touch customer success accounts.',
    blockers: ['Support team backlog during peak deployment windows.'],
    synapticInsights: {
      driveFiles: ['Client_Health_Scorecard_Q2.xlsx', 'NPS_Survey_Questions_2025.pdf'],
      emails: ['Client Escalation: Response SLA inquiry', 'Q2 Customer Health Review'],
      calendarEvents: ['Bi-weekly Client Success Alignment'],
      notionPages: ['Client Escalation Protocols', 'CS Playbook 2025'],
    },
  },
  {
    id: 'goal-3',
    title: 'Learn Advanced AI',
    category: 'Learning',
    description: 'Complete an advanced AI course and build 2 projects.',
    progress: 35,
    targetDate: 'Aug 31, 2025',
    priority: 'Medium priority',
    status: 'on_track',
    iconType: 'brain',
    iconTheme: 'amber',
    successMetric: '10 course modules passed & 2 production agent repos deployed',
    nextAction: {
      title: 'Continue lesson 4',
      time: 'In 2 days',
      type: 'video',
      context: 'Module 4: Multi-Agent Orchestration and Structured Output Decoding.',
    },
    connectedSources: [
      {
        id: 'src-3-1',
        type: 'youtube',
        name: 'YouTube / Course',
        detail: 'Advanced Reasoning & Antigravity Agent Patterns',
        snippet: 'Video lecture 4/10: State Synchronization & Context Windows',
        time: '3 days ago',
      },
      {
        id: 'src-3-2',
        type: 'notion',
        name: 'Notion',
        detail: 'AI Research Notes & Code Snippets',
        snippet: 'Synthesized summaries of attention mechanisms and vector embeddings',
        time: 'May 12',
      },
    ],
    moreSourcesCount: 1,
    milestones: [
      {
        id: 'm-3-1',
        title: 'Complete Core LLM Architecture Modules (1-3)',
        targetDate: 'May 01, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
      {
        id: 'm-3-2',
        title: 'Build Project 1: Autonomous Research Agent',
        targetDate: 'Jul 15, 2025',
        daysRemaining: 60,
        isCompleted: false,
        status: 'in_progress',
      },
      {
        id: 'm-3-3',
        title: 'Build Project 2: Real-time Multi-Modal Assistant',
        targetDate: 'Aug 31, 2025',
        daysRemaining: 107,
        isCompleted: false,
        status: 'upcoming',
      },
    ],
    aiReasoning:
      'Learning pace is steady. Dedicating a recurring 2-hour deep work block on Saturday mornings will bring completion forward by 2 weeks.',
  },
  {
    id: 'goal-4',
    title: 'Health & Fitness',
    category: 'Personal',
    description: 'Work out 4 days a week and maintain a healthy routine.',
    progress: 75,
    targetDate: 'Jun 30, 2025',
    priority: 'Low priority',
    status: 'on_track',
    iconType: 'heart',
    iconTheme: 'rose',
    successMetric: '4 weekly sessions logged consistently for 12 consecutive weeks',
    nextAction: {
      title: 'Evening workout',
      time: 'Today, 7:00 PM',
      type: 'health',
      context: 'Upper Body & Core hypertrophy session at the gym.',
    },
    connectedSources: [
      {
        id: 'src-4-1',
        type: 'calendar',
        name: 'Google Calendar',
        detail: 'Gym Workout - Hypertrophy Block',
        snippet: 'Recurring slot 7:00 PM – 8:15 PM (Protected Focus)',
        time: 'Today, 7:00 PM',
      },
      {
        id: 'src-4-2',
        type: 'health',
        name: 'Apple Health',
        detail: 'Weekly Activity Sync',
        snippet: '3 of 4 workouts completed this week • 520 avg active calories',
        time: 'Synced 1h ago',
      },
    ],
    milestones: [
      {
        id: 'm-4-1',
        title: 'Establish 4x Weekly Consistency for 4 Weeks',
        targetDate: 'Apr 30, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
      {
        id: 'm-4-2',
        title: 'Reach 8 Consecutive Weeks Streak',
        targetDate: 'May 31, 2025',
        daysRemaining: 15,
        isCompleted: false,
        status: 'in_progress',
      },
      {
        id: 'm-4-3',
        title: 'Complete 12-Week Transformation Phase',
        targetDate: 'Jun 30, 2025',
        daysRemaining: 45,
        isCompleted: false,
        status: 'upcoming',
      },
    ],
    aiReasoning:
      'High consistency score (92%). Evening calendar protection is successfully preventing scheduling collisions.',
  },
  {
    id: 'goal-5',
    title: 'Read 24 Books',
    category: 'Personal',
    description: 'Build a habit of reading and complete 24 books this year.',
    progress: 20,
    targetDate: 'Dec 31, 2025',
    priority: 'Low priority',
    status: 'on_track',
    iconType: 'book',
    iconTheme: 'blue',
    successMetric: '24 non-fiction and craft books read with chapter key takeaways logged in Notion',
    nextAction: {
      title: 'Read 20 pages',
      time: 'Sat, May 17',
      type: 'book',
      context: 'Current book: "Designing Data-Intensive Applications" (Chapter 4).',
    },
    connectedSources: [
      {
        id: 'src-5-1',
        type: 'notion',
        name: 'Notion',
        detail: '2025 Reading List & Book Vault',
        snippet: '5 of 24 books finished • 1 in progress ("Designing Data-Intensive Applications")',
        time: 'Yesterday',
      },
    ],
    milestones: [
      {
        id: 'm-5-1',
        title: 'Finish 6 Books by End of Q1',
        targetDate: 'Mar 31, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
      {
        id: 'm-5-2',
        title: 'Finish 12 Books by End of Q2',
        targetDate: 'Jun 30, 2025',
        daysRemaining: 45,
        isCompleted: false,
        status: 'in_progress',
      },
      {
        id: 'm-5-3',
        title: 'Complete 24 Books Milestone',
        targetDate: 'Dec 31, 2025',
        daysRemaining: 230,
        isCompleted: false,
        status: 'upcoming',
      },
    ],
    aiReasoning:
      'You are currently at 5 books completed. Reading 15-20 pages during quiet evening winding down will maintain target velocity.',
  },
  {
    id: 'goal-6',
    title: 'Build Developer Portfolio',
    category: 'Work',
    description: 'Create a modern interactive showcase for AI and distributed systems engineering.',
    progress: 0,
    targetDate: 'Sep 30, 2025',
    priority: 'Medium priority',
    status: 'not_started',
    iconType: 'code',
    iconTheme: 'indigo',
    successMetric: 'Live domain deployed with 4 interactive case studies and live demo sandboxes',
    nextAction: {
      title: 'Draft wireframe in Figma',
      time: 'Next week',
      type: 'document',
      context: 'Outline component architecture and project narrative structure.',
    },
    connectedSources: [
      {
        id: 'src-6-1',
        type: 'github',
        name: 'GitHub',
        detail: 'personal-portfolio-v3 repository',
        snippet: 'Initialized repository structure with Next.js 15 App Router & Tailwind CSS',
        time: '4 days ago',
      },
    ],
    milestones: [
      {
        id: 'm-6-1',
        title: 'Design UI Wireframes & Architecture Spec',
        targetDate: 'Jun 30, 2025',
        daysRemaining: 45,
        isCompleted: false,
        status: 'upcoming',
      },
      {
        id: 'm-6-2',
        title: 'Build Interactive Case Studies',
        targetDate: 'Aug 15, 2025',
        daysRemaining: 91,
        isCompleted: false,
        status: 'upcoming',
      },
      {
        id: 'm-6-3',
        title: 'Launch on Custom Domain',
        targetDate: 'Sep 30, 2025',
        daysRemaining: 137,
        isCompleted: false,
        status: 'upcoming',
      },
    ],
    aiReasoning:
      'Goal is scheduled to commence after Project Alpha Launch is delivered, preventing split cognitive focus.',
  },
];

export const ARCHIVED_GOALS: GoalItem[] = [
  {
    id: 'goal-archived-1',
    title: 'Q1 SOC2 Compliance & Security Audit',
    category: 'Work',
    description: 'Complete SOC2 Type 1 readiness review and pass external penetration audits.',
    progress: 100,
    targetDate: 'Mar 31, 2025',
    priority: 'High priority',
    status: 'completed',
    iconType: 'zap',
    iconTheme: 'purple',
    successMetric: 'Zero high severity findings in final third-party pentest report',
    nextAction: {
      title: 'Audit completed successfully',
      time: 'Archived Mar 31',
    },
    connectedSources: [
      {
        id: 'src-arch-1',
        type: 'drive',
        name: 'Google Drive',
        detail: 'SOC2_Type1_Final_Report.pdf',
        snippet: 'Official compliance certificate issued by Prescient Security',
        time: 'Mar 31',
      },
    ],
    milestones: [
      {
        id: 'm-arch-1',
        title: 'Policy Documentation & Role-Based Access Controls',
        targetDate: 'Feb 15, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
      {
        id: 'm-arch-2',
        title: 'External Penetration Testing Signoff',
        targetDate: 'Mar 31, 2025',
        daysRemaining: 0,
        isCompleted: true,
        status: 'completed',
      },
    ],
    aiReasoning: 'Successfully executed on schedule with 100% compliance score.',
    isArchived: true,
  },
];

export const AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec-1',
    title: 'Focus on Project Alpha Launch',
    description: 'It has the highest impact and is at risk.',
    targetGoalId: 'goal-1',
    impact: 'High Impact',
    actionLabel: 'Open Project Alpha Workspace',
    actionType: 'review_pricing',
    fullExplanation:
      'Project Alpha Launch is scheduled for Jun 30 (45 days remaining) and carries the highest organizational leverage. Resolving the open pricing strategy and SLA terms in Gmail today will unblock engineering beta provisioning and client review cycles.',
  },
  {
    id: 'rec-2',
    title: 'You can complete Learn Advanced AI faster by dedicating 2h on weekends.',
    description: 'Dedicate 2h on Saturday mornings to maintain a 10-week graduation pace.',
    targetGoalId: 'goal-3',
    impact: 'Pacing Boost',
    actionLabel: 'Schedule Weekend Study Block',
    actionType: 'schedule_focus',
    fullExplanation:
      'Historical study logs show your retention and code output are 2.4x higher on quiet Saturday mornings before 11:00 AM. Setting a calendar focus block will accelerate module completion by 14 days.',
  },
  {
    id: 'rec-3',
    title: 'Consider delegating tasks to speed up Improve Client Satisfaction.',
    description: 'Offload routine ticket triage to keep high-touch client accounts healthy.',
    targetGoalId: 'goal-2',
    impact: 'Bandwidth Unblock',
    actionLabel: 'Review Delegation Options',
    actionType: 'delegate',
    fullExplanation:
      'Client NPS is currently pacing behind quarterly target (42% vs expected 58%). Offloading routine bug reports and ticket triage to support team leads will create 6 weekly hours of direct stakeholder attention for strategic enterprise accounts.',
  },
];

export const ALL_UPCOMING_MILESTONES: MilestoneItem[] = [
  {
    id: 'm-1-4',
    title: 'Project Alpha Launch',
    goalTitle: 'Project Alpha Launch',
    targetDate: 'Jun 30, 2025',
    daysRemaining: 45,
    isCompleted: false,
    status: 'upcoming',
    category: 'Work',
  },
  {
    id: 'm-2-3',
    title: 'Improve Client Satisfaction',
    goalTitle: 'Improve Client Satisfaction',
    targetDate: 'Jun 30, 2025',
    daysRemaining: 45,
    isCompleted: false,
    status: 'upcoming',
    category: 'Work',
  },
  {
    id: 'm-3-3',
    title: 'Learn Advanced AI',
    goalTitle: 'Learn Advanced AI',
    targetDate: 'Aug 31, 2025',
    daysRemaining: 107,
    isCompleted: false,
    status: 'upcoming',
    category: 'Learning',
  },
  {
    id: 'm-4-3',
    title: 'Complete 12-Week Transformation Phase',
    goalTitle: 'Health & Fitness',
    targetDate: 'Jun 30, 2025',
    daysRemaining: 45,
    isCompleted: false,
    status: 'upcoming',
    category: 'Personal',
  },
  {
    id: 'm-5-2',
    title: 'Finish 12 Books by End of Q2',
    goalTitle: 'Read 24 Books',
    targetDate: 'Jun 30, 2025',
    daysRemaining: 45,
    isCompleted: false,
    status: 'upcoming',
    category: 'Personal',
  },
  {
    id: 'm-6-3',
    title: 'Launch Developer Portfolio on Custom Domain',
    goalTitle: 'Build Developer Portfolio',
    targetDate: 'Sep 30, 2025',
    daysRemaining: 137,
    isCompleted: false,
    status: 'upcoming',
    category: 'Work',
  },
];
