'use client';

import { ChangeFeedItem, ActiveSourceStat } from './types';

export const INITIAL_CHANGE_ITEMS: ChangeFeedItem[] = [
  // Today Group
  {
    id: 'chg-1',
    title: 'Project Alpha deadline changed',
    contextSubtitle: 'May 20 → May 22',
    sourceId: 'calendar',
    sourceName: 'Google Calendar',
    timeSection: 'Today',
    timeFilterGroup: 'Today',
    timestamp: '9:41 AM',
    importance: 'important',
    category: 'calendar',
    isRead: false,
    iconType: 'calendar',
    priorityBadge: 'High Priority',
    badgeDotColor: 'blue',
    previousValue: 'May 20, 2024',
    newValue: 'May 22, 2024',
    whatChanged: 'Project Alpha deadline was moved to May 22, 2024 (previously May 20).',
    whyItMatters: 'Provides additional runway for API testing before the executive milestone review.',
    relatedContext: [
      {
        sourceId: 'calendar',
        sourceName: 'Google Calendar',
        title: 'Project Alpha Sync',
        snippet: 'Updated invite details with May 22 deadline',
        timestamp: '9:41 AM',
      },
    ],
    recommendedAction: {
      label: 'Open event',
      actionType: 'open_source',
    },
  },
  {
    id: 'chg-2',
    title: 'Rahul replied',
    contextSubtitle: '“Looks good, let\'s move forward.”',
    sourceId: 'gmail',
    sourceName: 'Gmail',
    timeSection: 'Today',
    timeFilterGroup: 'Today',
    timestamp: '9:15 AM',
    importance: 'important',
    category: 'messages',
    isRead: false,
    iconType: 'mail',
    personName: 'Rahul Patel',
    personAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    badgeDotColor: 'purple',
    previousValue: 'Awaiting client response',
    newValue: 'Client approved ("Looks good, let\'s move forward.")',
    whatChanged: 'Rahul approved the Project Alpha commercial terms and gave green light to proceed.',
    whyItMatters: 'Unblocks Phase 1 development and allows budget allocation.',
    relatedContext: [
      {
        sourceId: 'gmail',
        sourceName: 'Gmail',
        title: 'Re: Project Alpha Proposal',
        snippet: '"Looks good, let\'s move forward with Phase 1..."',
        timestamp: '9:15 AM',
      },
    ],
    recommendedAction: {
      label: 'Open email',
      actionType: 'prepare_response',
    },
  },
  {
    id: 'chg-3',
    title: 'Proposal v2.3 uploaded',
    contextSubtitle: 'proposal_v2.3.pdf',
    sourceId: 'drive',
    sourceName: 'Google Drive',
    timeSection: 'Today',
    timeFilterGroup: 'Today',
    timestamp: '8:02 AM',
    importance: 'relevant',
    category: 'files',
    isRead: false,
    iconType: 'doc',
    badgeDotColor: 'emerald',
    previousValue: 'proposal_v2.2.pdf',
    newValue: 'proposal_v2.3.pdf',
    whatChanged: 'Updated PDF uploaded containing revised scope breakdown.',
    whyItMatters: 'Final document version ready for client signing.',
    relatedContext: [
      {
        sourceId: 'drive',
        sourceName: 'Google Drive',
        title: 'proposal_v2.3.pdf',
        snippet: 'Modified 8:02 AM by Sarah Jenkins',
        timestamp: '8:02 AM',
      },
    ],
    recommendedAction: {
      label: 'Open file',
      actionType: 'open_source',
    },
  },

  // Yesterday Group
  {
    id: 'chg-4',
    title: 'Project Alpha Hub updated',
    contextSubtitle: '3 pages updated in Notion workspace',
    sourceId: 'notion',
    sourceName: 'Notion',
    timeSection: 'Yesterday',
    timeFilterGroup: 'Yesterday',
    timestamp: '7:30 PM',
    importance: 'relevant',
    category: 'files',
    isRead: true,
    iconType: 'doc',
    badgeDotColor: 'purple',
    previousValue: '2 pages updated',
    newValue: '3 new pages added to Notion workspace',
    whatChanged: 'Architecture and API specification docs were updated by team.',
    whyItMatters: 'Ensures technical design documents stay up to date for Sprint 28.',
    relatedContext: [
      {
        sourceId: 'notion',
        sourceName: 'Notion',
        title: 'Project Alpha Hub',
        snippet: '3 pages updated: API Spec, System Design, Release Checklist',
        timestamp: '7:30 PM',
      },
    ],
    recommendedAction: {
      label: 'Open page',
      actionType: 'open_source',
    },
  },
  {
    id: 'chg-5',
    title: 'New email from Priya',
    contextSubtitle: 'Subject: Budget review for Project Alpha',
    sourceId: 'gmail',
    sourceName: 'Gmail',
    timeSection: 'Yesterday',
    timeFilterGroup: 'Yesterday',
    timestamp: '4:45 PM',
    importance: 'relevant',
    category: 'messages',
    isRead: true,
    iconType: 'mail',
    personName: 'Priya Sharma',
    personAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    badgeDotColor: 'blue',
    previousValue: 'Draft',
    newValue: 'Email received with budget review request',
    whatChanged: 'Priya sent financial breakdown for review.',
    whyItMatters: 'Requires input before final budget freeze on Friday.',
    relatedContext: [
      {
        sourceId: 'gmail',
        sourceName: 'Gmail',
        title: 'Budget review for Project Alpha',
        snippet: 'Attached line item calculations for compute and tooling.',
        timestamp: '4:45 PM',
      },
    ],
    recommendedAction: {
      label: 'Open email',
      actionType: 'prepare_response',
    },
  },

  // Earlier Group
  {
    id: 'chg-6',
    title: 'Budget Sheet updated',
    contextSubtitle: 'alpha_budget_v2.xlsx',
    sourceId: 'drive',
    sourceName: 'Google Drive',
    timeSection: 'Earlier',
    timeFilterGroup: 'This Month',
    timestamp: 'May 10',
    importance: 'informational',
    category: 'files',
    isRead: true,
    iconType: 'doc',
    badgeDotColor: 'emerald',
    previousValue: 'alpha_budget_v1.xlsx',
    newValue: 'alpha_budget_v2.xlsx',
    whatChanged: 'Financial spreadsheet updated with Q3 compute figures.',
    whyItMatters: 'Reflects approved cloud infrastructure pricing.',
    relatedContext: [
      {
        sourceId: 'drive',
        sourceName: 'Google Drive',
        title: 'alpha_budget_v2.xlsx',
        snippet: 'Updated May 10 by Finance Team',
        timestamp: 'May 10',
      },
    ],
    recommendedAction: {
      label: 'Open file',
      actionType: 'open_source',
    },
  },
];

export const MOCK_MOST_ACTIVE_SOURCES: ActiveSourceStat[] = [
  { sourceId: 'gmail', sourceName: 'Gmail', count: 6 },
  { sourceId: 'calendar', sourceName: 'Google Calendar', count: 4 },
  { sourceId: 'drive', sourceName: 'Google Drive', count: 3 },
  { sourceId: 'slack', sourceName: 'Slack', count: 3 },
  { sourceId: 'notion', sourceName: 'Notion', count: 2 },
];

export const WEEKLY_ACTIVITY_DATA = [
  { day: 'M', count: 12, active: false },
  { day: 'T', count: 15, active: false },
  { day: 'W', count: 14, active: false },
  { day: 'T', count: 18, active: true }, // Current active day in reference screenshot
  { day: 'F', count: 11, active: false },
  { day: 'S', count: 7, active: false },
  { day: 'S', count: 9, active: false },
];
