import { PluginItem } from './types';

export const INITIAL_PLUGIN_CATALOG: PluginItem[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read, search and manage your emails.',
    category: 'Communication',
    provider: 'Google',
    authMethod: 'google_oauth',
    connectionStatus: 'NOT_CONNECTED',
    enabled: true,
    popularRank: 1,
    requiredScopes: ['https://www.googleapis.com/auth/gmail.readonly'],
    capabilities: [
      {
        id: 'search_email',
        name: 'Search Email',
        description: 'Find relevant threads and query inbox message content.',
      },
      {
        id: 'read_email',
        name: 'Read Email Messages',
        description: 'Extract context and parse attachments for task execution.',
      },
      {
        id: 'create_draft',
        name: 'Draft Replies',
        description: 'Draft contextual email replies for user review.',
      },
    ],
  },
  {
    id: 'drive',
    name: 'Google Drive',
    description: 'Search, read and manage your files.',
    category: 'Storage',
    provider: 'Google',
    authMethod: 'google_oauth',
    connectionStatus: 'NOT_CONNECTED',
    enabled: true,
    popularRank: 2,
    requiredScopes: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/drive.activity',
      'https://www.googleapis.com/auth/drive.activity.readonly',
      'https://www.googleapis.com/auth/drive.appdata',
      'https://www.googleapis.com/auth/drive.apps.readonly',
      'https://www.googleapis.com/auth/drive.file',
      'https://www.googleapis.com/auth/drive.install',
      'https://www.googleapis.com/auth/drive.meet.readonly',
      'https://www.googleapis.com/auth/drive.metadata',
      'https://www.googleapis.com/auth/drive.metadata.readonly',
      'https://www.googleapis.com/auth/drive.photos.readonly',
      'https://www.googleapis.com/auth/drive.readonly',
      'https://www.googleapis.com/auth/drive.scripts'
    ],
    capabilities: [
      {
        id: 'search_files',
        name: 'Search Files & Folders',
        description: 'Query document titles, metadata, and folders across Drive.',
      },
      {
        id: 'read_files',
        name: 'Read Documents & Sheets',
        description: 'Extract textual and spreadsheet data for automated processing.',
      },
    ],
  },
  {
    id: 'calendar',
    name: 'Google Calendar',
    description: 'View schedules, events and manage meetings.',
    category: 'Productivity',
    provider: 'Google',
    authMethod: 'google_oauth',
    connectionStatus: 'NOT_CONNECTED',
    enabled: true,
    popularRank: 3,
    requiredScopes: ['https://www.googleapis.com/auth/calendar.readonly'],
    capabilities: [
      {
        id: 'read_events',
        name: 'Read Calendar Events',
        description: 'View scheduled meetings and upcoming event agendas.',
      },
      {
        id: 'check_availability',
        name: 'Check Free/Busy Availability',
        description: 'Determine available time slots for scheduling coordination.',
      },
    ],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Access pages, databases and workspace content.',
    category: 'Productivity',
    provider: 'Notion',
    authMethod: 'notion_oauth',
    connectionStatus: 'NOT_CONNECTED',
    enabled: true,
    popularRank: 4,
    requiredScopes: ['read_content', 'read_user'],
    capabilities: [
      {
        id: 'query_databases',
        name: 'Query Databases',
        description: 'Fetch filtered rows and views from team workspace databases.',
      },
      {
        id: 'read_pages',
        name: 'Read Pages & Blocks',
        description: 'Retrieve structured documentation, specs, and meeting notes.',
      },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Get messages, search channels and more.',
    category: 'Communication',
    provider: 'Slack',
    authMethod: 'slack_oauth',
    connectionStatus: 'NOT_CONNECTED',
    enabled: true,
    popularRank: 5,
    requiredScopes: ['channels:read', 'chat:write', 'users:read'],
    capabilities: [
      {
        id: 'read_channels',
        name: 'Read Channels & Messages',
        description: 'Search communication channels and fetch thread context.',
      },
      {
        id: 'send_notifications',
        name: 'Send Work Updates',
        description: 'Post structured task summaries and approval notifications.',
      },
    ],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Access repositories, issues and pull requests.',
    category: 'Developer',
    provider: 'GitHub',
    authMethod: 'github_oauth',
    connectionStatus: 'NOT_CONNECTED',
    enabled: true,
    popularRank: 6,
    requiredScopes: ['repo', 'read:user'],
    capabilities: [
      {
        id: 'read_repos',
        name: 'Read Repositories & Code',
        description: 'Explore repository codebases, branches, and commit histories.',
      },
      {
        id: 'read_issues',
        name: 'Manage Issues & Pull Requests',
        description: 'Inspect open issues, PR reviews, and pull request diffs.',
      },
    ],
  },
];
